In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
import warnings
warnings.filterwarnings('ignore')
import time
import requests
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [21]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import pandas as pd

# Initialize Chrome WebDriver (make sure to download chromedriver.exe and place it in your PATH)
driver = webdriver.Chrome()

# URL of the first page
base_url = "https://www.mrmed.in/products"

lists = []

# Loop through 5 pages
for page in range(1, 5):
    url = base_url.format(page)
    driver.get(url)
    
    # Wait for the page to load (adjust the sleep time as needed)
    time.sleep(3)
    
    # Find elements for name and storage
    names = driver.find_elements(By.XPATH, '//div[@class="ProductCard_mrp__2LCND"]')
    storages = driver.find_elements(By.XPATH, '//div[@class="ProductCard_salt_name__W2S3q"]')
    Med = driver.find_elements(By.XPATH, '//div[@class="ProductCard_product_title__3ZtHe"]')
    
    # Check if lengths match
    if len(names) != len(storages):
        print(f"Error on page {page}: Lengths of names and storages do not match.")
        continue
    
    # Append data to lists
    for i in range(len(names)):
        lists.append([names[i].text, storages[i].text, Med[i].text])
    
# Close the WebDriver
driver.quit()

# Create a DataFrame
df = pd.DataFrame(lists, columns=['Name', 'Storage', 'Med'])

# Print the DataFrame
#print(df)
#split_df = pd.DataFrame(df['Name'].str.split('\n', expand=True))
#split_df.rename(columns={0: 'Name', 1: 'Qty', 2: 'Salt', 3: 'Company'}, inplace = True)
#Price = df[['Storage']].rename(columns = {'Storage':'Price'})
#Data_D = pd.concat([split_df, Price], axis = 1)

In [26]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import pandas as pd

# Initialize Chrome WebDriver (make sure to download chromedriver.exe and place it in your PATH)
driver = webdriver.Chrome()

# URL of the first page
base_url = "https://www.mrmed.in/products?page={}"

lists = []

# Loop through 5 pages
for page in range(1, 335):  # Changed range to fetch 5 pages
    url = base_url.format(page)
    driver.get(url)
    
    # Wait for the page to load (adjust the sleep time as needed)
    time.sleep(3)
    
    # Find elements for name, storage, and medicine details
    names = driver.find_elements(By.XPATH, '//div[@class="ProductCard_mrp__2LCND"]')
    storages = driver.find_elements(By.XPATH, '//div[@class="ProductCard_salt_name__W2S3q"]')
    meds = driver.find_elements(By.XPATH, '//div[@class="ProductCard_product_title__3ZtHe"]')
    
    # Check if lengths match
    if len(names) != len(storages) or len(names) != len(meds):
        print(f"Error on page {page}: Lengths of names, storages, and meds do not match.")
        continue
    
    # Append data to lists
    for i in range(len(names)):
        lists.append([names[i].text, storages[i].text, meds[i].text])
    
# Close the WebDriver
driver.quit()

# Create a DataFrame
df = pd.DataFrame(lists, columns=['Name', 'Storage', 'Medicine'])

# Print the DataFrame
#print(df.head())  # Print first few rows of the DataFrame

In [31]:
df

,Name,Storage,Medicine
0,MRP\n:\n₹990,Salt Composition : 2-DEOXY-D-GLUCOSE\nManufact...,2DG 2.34gm Sachet\nPrescription
1,MRP\n:\n₹15.15,Salt Composition : FLUOROURACIL\nManufacturer ...,5 Flucel 250mg Injection\nPrescription
2,MRP\n:\n₹30.25,Salt Composition : FLUOROURACIL\nManufacturer ...,5 Flucel 500mg Injection\nPrescription
3,MRP\n:\n₹13.5,Salt Composition : FLUOROURACIL\nManufacturer ...,5FU GLS 250mg Injection\nPrescription
4,MRP\n:\n₹27,Salt Composition : FLUOROURACIL\nManufacturer ...,5FU GLS 500mg Injection\nPrescription
...,...,...,...
6655,MRP\n:\n₹1116,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Zyrop 3000 IU Injection\nPrescription
6656,MRP\n:\n₹1677,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Zyrop 4000 IU Injection\nPrescription
6657,MRP\n:\n₹1648.5,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Zyrop 5000 IU Injection\nPrescription
6658,MRP\n:\n₹1800,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Zyrop 6000 IU Injection\nPrescription
6659,MRP\n:\n₹12638.5,Salt Composition : DOCETAXEL\nManufacturer : Z...,Zytax 120mg Injection\nPrescription\nCold Chain

In [28]:
df['Name'].str.split('\n', expand=True)

        0  1         2
0     MRP  :      ₹990
1     MRP  :    ₹15.15
2     MRP  :    ₹30.25
3     MRP  :     ₹13.5
4     MRP  :       ₹27
...   ... ..       ...
6655  MRP  :     ₹1116
6656  MRP  :     ₹1677
6657  MRP  :   ₹1648.5
6658  MRP  :     ₹1800
6659  MRP  :  ₹12638.5

[6660 rows x 3 columns]

In [29]:
df['Storage'].str.split('\n', expand=True)

,0,1
0,Salt Composition : 2-DEOXY-D-GLUCOSE,Manufacturer : DR REDDY'S LABORATORIES LTD
1,Salt Composition : FLUOROURACIL,Manufacturer : CELON LABORATORIES LTD
2,Salt Composition : FLUOROURACIL,Manufacturer : CELON LABORATORIES LTD
3,Salt Composition : FLUOROURACIL,Manufacturer : GLS PHARMA LTD
4,Salt Composition : FLUOROURACIL,Manufacturer : GLS PHARMA LTD
...,...,...
6655,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Manufacturer : ZYDUS CADILA
6656,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Manufacturer : ZYDUS CADILA
6657,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Manufacturer : ZYDUS CADILA
6658,Salt Composition : RECOMBINANT HUMAN ERYTHROPO...,Manufacturer : ZYDUS CADILA
6659,Salt Composition : DOCETAXEL,Manufacturer : ZYDUS CADILA

In [30]:
df['Medicine'].str.split('\n', expand=True)

                             0             1           2
0            2DG 2.34gm Sachet  Prescription        None
1     5 Flucel 250mg Injection  Prescription        None
2     5 Flucel 500mg Injection  Prescription        None
3      5FU GLS 250mg Injection  Prescription        None
4      5FU GLS 500mg Injection  Prescription        None
...                        ...           ...         ...
6655   Zyrop 3000 IU Injection  Prescription        None
6656   Zyrop 4000 IU Injection  Prescription        None
6657   Zyrop 5000 IU Injection  Prescription        None
6658   Zyrop 6000 IU Injection  Prescription        None
6659     Zytax 120mg Injection  Prescription  Cold Chain

[6660 rows x 3 columns]

In [32]:
# Save to Excel
excel_file = 'scraped_data.xlsx'
df.to_excel(excel_file, index=False)

print(f"Data saved to {excel_file}")

Data saved to scraped_data.xlsx